# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zUfl7jqXR_kDnzzVKoCQoWIM773rKols
"""

import gspread
from google.colab import auth
from googleapiclient.discovery import build
import google.auth

auth.authenticate_user()


def conectar_google_sheets(sheet_name):
    creds, _ = google.auth.default()
    service = build("sheets", "v4", credentials=creds)
    gc = gspread.authorize(creds)
    sheet = gc.open(sheet_name).sheet1
    return sheet

SHEET_NAME = "peças cadastradas"

sheet = conectar_google_sheets(SHEET_NAME)


codigo = input("Código da Peça: ")
descricao = input("Descrição da Peça: ")

if codigo and descricao:
    sheet.append_row([codigo, descricao])
    print("✅ Peça cadastrada com sucesso!")
else:
    print("❌ Por favor, preencha todos os campos.")

    !python Untitled6.py